name: build server
on:
  pull_request:
      paths:
      - "carbonserver/**"
      - "pyproject.toml"
  push:
    paths:
      - "carbonserver/**"
      - "pyproject.toml"
    branches: [master]
jobs:
  build_server:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    - name: Set up Python
      run: uv python install 3.12
    - name: Install dependencies
      run: uv sync --extra api
    - name: Unit tests on api
      run: uv run task test-api-unit
  test_api_server:
    runs-on: ubuntu-latest
    # Service containers to run with `container-job`
    services:
      # Label used to access the service container
      postgres:
        # Docker Hub image
        image: postgres:16
        # Provide the password for postgres
        env:
          POSTGRES_DB: codecarbon_db
          POSTGRES_PASSWORD: supersecret
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          # Maps tcp port 5432 on service container to the host
          - 5432:5432
    steps:
    - uses: actions/checkout@v4
    - name: Install uv
      uses: astral-sh/setup-uv@v3
      with:
        version: "latest"
    - name: Set up Python
      run: uv python install 3.12
    - name: Install dependencies
      run: uv sync --extra api
    - name: Setup database
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PASSWORD: supersecret
        POSTGRES_USER: postgres
        POSTGRES_DB: codecarbon_db
        POSTGRES_PORT: 5432
      run: uv run task setup-db
    - name: Integration tests on api
      env:
        POSTGRES_HOST: localhost
        POSTGRES_PASSWORD: supersecret
        POSTGRES_USER: postgres
        POSTGRES_DB: codecarbon_db
        POSTGRES_PORT: 5432
      run: |
        # uv run task dashboard-ci &
        # sleep 10  # wait for server to start
        # netstat -o -n -a | grep 8008
        # uv run task test-api-integ
        echo "Integration tests temporarily disabled - need to fix server startup"
